### ISSUE TITLE
What is the exception in the `plot_with_eventsfile`

### ISSUE THREAD

**Issue by yeroslaviz** [Xinglab/rmats2sashimiplot#100]
Hi,

thanks a lot for a great tool. I am using it now to analyze a smart-seq2 data set, I have also analyzed with `rMATS`. In total I have two groups of samples (control vs. treatment), each of them has 24 samples.

After running `rMATS`I have the junction files for the different events and I use them to run `rmats2shshimiplot`.

I have downloaded the latest github repository, so I think I have the latest version. 

The command I use is:

```
python $rmats2sashimiplot --l1 cre_pos --l2 cre_neg --b1 pos_samples.txt --b2 neg_samples.txt  \
                          --exon_s 1 --intron_s 5 --group-info grouping.gf \
                          --event-type SE -e rMATS_output/SE.MATS.JC.sig.txt \
                          -o SE.MATS.JC.sig.groups
```
I'm attaching here the head of the event file I used. 

But the output always gives me warnings and errors such as shown below.
Also at the end of the run, after it produces many plots it throws another error, before finishing (s. below)

```
Warning: The inclusion levels of Event '19_9861269_9861383_-@19_9861063_9861197_-@19_9855683_9855792_-' contains 'NA' value, which could lead to unexpected output.
<module 'misopy' from '
...
Reading sample label: Incenp firstGroup IncLevel: nan
Skipping read with CIGAR 9M70N12M1D97M5270N33M
Skipping read with CIGAR 37M5270N72M1D39M
Skipping read with CIGAR 10M5270N47M1I90M
Skipping read with CIGAR 10M5270N50M1I87M
...

#here comes the error:
invalid literal for int() with base 10: ''
There is an exception in plot_with_eventsfile
Traceback (most recent call last):
  File "rmats2sashimiplot/src/rmats2sashimiplot/rmats2sashimiplot.py", line 953, in <module>
    main()
  File "rmats2sashimiplot/src/rmats2sashimiplot/rmats2sashimiplot.py", line 949, in main
    plot_with_eventsfile(options)
  File "rmats2sashimiplot/src/rmats2sashimiplot/rmats2sashimiplot.py", line 626, in plot_with_eventsfile
    coor = EventCoor(options.event_type, items)
  File "rmats2sashimiplot/src/rmats2sashimiplot/rmats2sashimiplot.py", line 496, in __init__
    self.se_s = str(int(items[5]) + 1)
ValueError: invalid literal for int() with base 10: ''
```

But when I count all the plots it has as many as rows in the input file, so i don't understand if i need to check it all or not.

thanks for the help

Assa

[eventstop.txt](https://github.com/Xinglab/rmats2sashimiplot/files/11742520/eventstop.txt)

**Comment by EricKutschera** [comment]
This is the line for the error: https://github.com/Xinglab/rmats2sashimiplot/blob/b1d6835e60f158a8717504794ab3e66220488337/src/rmats2sashimiplot/rmats2sashimiplot.py#L496

It's looking at the 6th tab separated column from the input event file and expecting to find the exon start coordinate. The error is saying that it found the empty string at that column. If you got a plot for every row of the input file then maybe the issue is with the formatting of the last line of your event file (maybe some extra whitespace). You could try adding a print statement right before this line to see what is causing the error: https://github.com/Xinglab/rmats2sashimiplot/blob/b1d6835e60f158a8717504794ab3e66220488337/src/rmats2sashimiplot/rmats2sashimiplot.py#L626

`print('line: {}'.format(line))`

**Comment by yeroslaviz** [comment]
I have found out what the problem was. Somehow I got some empty rows in my file of events after filtering for only the significant events (FDR <=0.05). but somehow the tabs were left in the file, so it throws this error. When I cleaned the files, the error was gone

Thanks for that
