### ISSUE TITLE
no pdf in the output

### ISSUE THREAD

**Issue by skytguuu** [Xinglab/rmats2sashimiplot#29]
Hi,
I tried to use rmats2sashimiplot to plot the figure. However, when I used the command:
###################
nohup rmats2sashimiplot --b1 cell1_rep1.bam,cell1_rep2.bam --b2 cell2_rep1.bam,cell2_rep2.bam -t MXE -e rMATs_res/AS/MXE.MATS.JC.txt --l1 cell1 --l2 cell2 -o MXE &
###################
I have checked the output, it is no any pdf or png output.  
The following picture was the output from one gene.
![image](https://user-images.githubusercontent.com/25957174/73115134-3ca24f80-3f5d-11ea-9abe-f1ef81ff4519.png)

**Comment by RacheliRap** [comment]
I got the same problem.
Any chance you figured it out?
Thanks!

**Comment by EricKutschera** [comment]
The files you show in the picture look like they're from the Sashimi_index/ directory which contains intermediate files used to create the plot. There was probably an error that caused the plot not to be created. Since you used `nohup` the error message may have been written to `nohup.out`

Several issues were addressed in recent code changes. Please open a new issue if needed after trying the latest source code
