### ISSUE TITLE
plot with one sample

### ISSUE THREAD

**Issue by zpliu1126** [Xinglab/rmats2sashimiplot#43]
Hi EricKutschera

when I run `rmats-turbo` to  identified AS with one sample using parameter `--statoff` ;
and then I want to use `rmats2sashimiplot` to Visualization of  AS events in one sample。 But `rmats2sashimiplot` only accept two samples such required parameters 
```bash
--s1
--s2
--l1
--l2
```
if I omission some import information。

**Comment by EricKutschera** [comment]
You can run the branch of rmats2sashimiplot from this pull request: https://github.com/Xinglab/rmats2sashimiplot/pull/42

That code change allows you to omit --s2. You'll still need to supply --l2 but the value will not be used.

Another solution is to use the same sample for both --s1 and --s2. Since the data is the same you'll get duplicate plots

**Comment by zpliu1126** [comment]
thank you ，I had use the same sample,and got duplicate plots
