### ISSUE TITLE
Multiple threads

### ISSUE THREAD

**Issue by czfoo** [Xinglab/rmats2sashimiplot#44]
Hi. I was wondering if there was a way to run this program on multiple threads to speed it up, since the node that I am using has multiple cores. Thanks.

**Comment by EricKutschera** [comment]
rmats2sashimiplot is not designed to use multiple threads. If you are making multiple plots using the rMATS event file as input then you could split the rows of that event file into smaller files so that you have one event file for each core on your node. Then you could start a separate instance of rmats2sashimiplot for each event file
