### ISSUE TITLE
Plotting only specific genes

### ISSUE THREAD

**Issue by czfoo** [Xinglab/rmats2sashimiplot#47]
Hi, I've noticed that each of the rMATs outputs has thousands of genes, and it will take up too much space and way too much time for me to make sashimi plots for every single one of them. Is there a way to specify the specific events I want to make sashimi plots for?

**Comment by EricKutschera** [comment]
rmats2sashimiplot will plot all the events in the file given to it as input with `-e`. Instead of using an rMATS output file directly (like SE.MATS.JC.txt), you could make a copy (SE.MATS.JC.filtered.txt) and modify that file so that it only contains the events that you want to plot. Then run rmats2sashimiplot with `-e SE.MATS.JC.filtered.txt`
