### ISSUE TITLE
The IJC_SAMPLE_1 values in SE.MATS.JC.txt is different from value showed in sashimi_plot

### ISSUE THREAD

**Issue by KunFang93** [Xinglab/rmats2sashimiplot#48]
Hi, 

I found that the counts' values showed in sashimi_plot are different from the counts' value in SE.MATS.JC.txt. I was wondering why this happens?  
For example:
In SE.MATS.JC.txt
```
2       "TMEM181"       "TMEM181"       chr6    +       159028275       159028375       159026298       159026379       159029364       159029495
       2       240     2                       100     50      NA      NA      0.984           NA
```
The IJC_SAMPLE_1 value is 240, but in sashimi_plot
<img width="669" alt="sashimiplot_issue" src="https://user-images.githubusercontent.com/15643651/100901151-27555600-3489-11eb-947c-e3fe06aee014.png">
the counts value= 98 +114, which is not equal to 240.

Thanks in advance!

Best,
Kun

**Comment by EricKutschera** [comment]
The counts are not expected to be exactly the same because rmats2sashimiplot uses MISO to do the counting and generate the plot. The count information from SE.MATS.JC.txt is not directly used. One possible explanation is that rmats may have filtered out some of the reads (maybe for not matching the read length or having extra cigar operations). There's a similar issue about the count differences with more details: https://github.com/Xinglab/rmats2sashimiplot/issues/33

**Comment by KunFang93** [comment]
Understand! Thanks for the prompt reply!
