### ISSUE TITLE
How to restrict the splicing analysis to events with 10 or more reads?

### ISSUE THREAD

**Issue by elva0328** [Xinglab/rmats2sashimiplot#60]
hello, when I use the rmats and rmats2sashimiplot, I encounter several problems:
1: How to restrict the analysis to events with 10 or more reads, which is a standard cutoff used in many research papers. and I wonder how to set it in the code.
2: how to explain the result from the rmats2sashimiplot? For example, in this case, which group has the skipped exon event, the control or the case? what's the meaning of the gtf plot under the figure, do these two lines represent the control and case status? 
![image](https://user-images.githubusercontent.com/53468690/121920465-b0cdc680-ccfd-11eb-91d9-d78e48a204c2.png)
 
really appreciate your response~

**Comment by EricKutschera** [comment]
1. If you are running rmats2sashimiplot with an rmats event file with the -e argument then you can write a script to filter that event file before running rmats2sashimiplot. I don't have a script to do exactly that, but here are some scripts that read rMATS output files. Maybe one of them will be a useful starting point for you to write a new script:
https://github.com/Xinglab/rmats-turbo/blob/v4.1.1/rMATS_P/summary.py#L70
https://github.com/Xinglab/rmats-turbo/blob/v4.1.1/rMATS_P/prepare_stat_inputs.py#L74


2. The junction reads are shown with the curved line that has a number in the middle of the line. In that plot, "control-1" has 3 junction reads that go from the left exon to the right exon. Those 3 reads "skip" the middle exon. The other junction reads are from the middle exon to the right exon (7 in "control-1" and 10 in "case-1"). Since only "control-1" has reads that skip the exon, you could say that only "control-1" has the skipped exon event. The gtf plot at the bottom is showing the two different isoforms for this event. That gtf plot is just based on the coordinates from the rmats event file that was given as input to rmats2sashimiplot. The top part (with 3 exons) is showing the inclusion isoform for this event. The bottom part is showing the skipping isoform

**Comment by elva0328** [comment]
thanks for your reply, that helped a lot.
I've checked the code of question 1( how to restrict the analysis to event with 10 or more reads). but didn't find out which parameter can be used to filter the reads. so what do you recommend for that?

**Comment by EricKutschera** [comment]
There's not an existing parameter to filter the reads. I was suggesting that you write your own program to filter the input file before running rmats2sashimiplot. The code I linked to earlier is only intended as an example of what that new script could look like

If you do write your own program, then you could do the filtering like this:

```
python your_script_to_filter_the_reads.py original_event_file.txt > filtered_event_file.txt
rmats2sashimiplot {other_arguments...} -e filtered_event_file.txt
```

**Comment by elva0328** [comment]
sure, got it. thank you
