### ISSUE TITLE
Result interpretation

### ISSUE THREAD

**Issue by elva0328** [Xinglab/rmats2sashimiplot#68]
hello, rmats2sashimiplot is a wonderful tool. I've already got the result, but I'm confused about how to interpret the result, could you help with this.
for example:
![splicing](https://user-images.githubusercontent.com/53468690/131539352-cbe669d9-36f0-4817-be70-db5bb698c994.png)
in this skipped exon event, we have samples 1-3, which sample has the SE event? or which sample has the increased SE event? and what additional information we can see from the result?
appreciate your response.

**Comment by EricKutschera** [comment]
All three samples "have the event" since there are reads that skip the exon and also reads that include the exon in each sample. Sample 1 has the lowest inclusion level (IncLevel: 0.31) so you could say that it shows an increase in the frequency of exon skipping compared to the other samples


This sashimiplot shows that there are no junction reads going from the left exon to the middle exon, but there are skipping junctions (96 in sample 1) and junctions going from the middle exon to the right exon (86 in sample 1). Ideally you would see similar numbers for the left junction and the right junction like in the plots from the rmats2sashimiplot README: https://github.com/Xinglab/rmats2sashimiplot/tree/v2.0.4

**Comment by elva0328** [comment]
thanks very much, Eric. but I still have one question, for skipped exon event, the samples with lower lncLevel show an increase in the frequency. how about for the other 4 splicing events, can we use the same standard to identify the samples with increase splicing eVent. such as the sample with lower lncLevel show an increase in the frequency of RI, MXE, A3SS,A5SS?

**Comment by elva0328** [comment]
@EricKutschera thanks very much. it helps me a lot!
