### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by tamerbio** [Xinglab/rmats2sashimiplot#83]
Hi,
I was trying to use this tool to get a sashimi plot but I had a syntax error message.
I ran the following command:
`python src/rmats2sashimiplot/rmats2sashimiplot.py  --b1 re1.bam --b2 rep2.bam -c chr8:-:121053451:121083734:gencode.vM25.primary_assembly.annotation.gff3 -o test_coordinate_output --l1 sampleOne --l2 sampleTwo`
but got the following error
```
'/Users/tali/Desktop/ENCFF992TVG.bam' is indexed already: 'rep1.bam.bai'
'/Users/tali/Desktop/ENCFF440YLP.bam' is indexed already: 'rep2.bam.bai'
  File "rmats2sashimiplot/src/MISO/misopy/index_gff.py", line 77
    print "Making directory: %s" %(chrom_dir)
          ^
SyntaxError: invalid syntax
  File "rmats2sashimiplot/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 46
    print "WARNING: %s does not end in .miso_bf, are you sure it is the " \
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("WARNING: %s does not end in .miso_bf, are you sure it is the " \)?
```
any idea how to solve it?
many many thanks
Tamer

**Comment by EricKutschera** [comment]
`SyntaxError: Missing parentheses in call to 'print'` happens if using Python3 with the unmodified rmats2sashimiplot code (which is Python2). Running `./2to3.sh` can convert to Python3: https://github.com/Xinglab/rmats2sashimiplot/blob/v2.0.4/2to3.sh

Here's a similar post: https://github.com/Xinglab/rmats2sashimiplot/issues/61#issuecomment-908325034

**Comment by tamerbio** [comment]
Hi Eric,
cool. how does it work?
thanks much
TA

**Comment by tamerbio** [comment]
many many thanks Eric. it worked
