### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by deb0612** [Xinglab/rmats2sashimiplot#87]
Dear sir,
When I use following command, and got the error message
rmats2sashimiplot --b1 "/home/user/cancer/Aligned.sortedByCoord.out.bam"  --b2 "/home/user/cancer/Aligned.sortedByCoord.out.bam" -t SE -e "/results/fromGTF.SE.txt" --l1 A --l2 B --exon_s 1 --intron_s 1 -o SE_plot -c chr16:+:9000:25000:gencode.v42.annotation.gff3
![image](https://user-images.githubusercontent.com/29038270/200793287-df95ef51-e149-4f32-bb95-61dfa19a4459.png)

**Comment by EricKutschera** [comment]
I think the error is from `-e fromGTF.SE.txt`. The -e parameter expects a MATS file like SE.MATS.JC.txt

https://github.com/Xinglab/rmats2sashimiplot/issues/86#issuecomment-1287341058

**Comment by deb0612** [comment]
Thanks!
But I got empty file of SE.MATS.JC.txt after running rmats
Here is the list of output files:
![image](https://user-images.githubusercontent.com/29038270/201004348-b96b1a7d-465b-46a0-83df-0fe67b8cc8ee.png)

**Comment by EricKutschera** [comment]
The .MATS files could be empty (just have the header) because reads are filtered out. rMATS will output a summary of how many reads were filtered described in this post: https://github.com/Xinglab/rmats-turbo/issues/89

Based on the file sizes you posted, it seems that the JC.raw.input.SE.txt file is not empty. I'm not sure why that file would have data when the .MATS file does not. Was there an error message when you ran rmats? What version of rmats did you use?
