### ISSUE TITLE
Issue with gff3 file 

### ISSUE THREAD

**Issue by Oliverfeudj** [Xinglab/rmats2sashimiplot#92]
Hello 
I am having an issue with gff3 file and I don't know what is wrong 

ValueError: invalid literal for int() with base 10: './Mus_musculus.GRCm39.108.gff3'

And here is my syntax:
rmats2sashimiplot --b1 spc_Aligned.sortedByCoord.out.bam \
  --b2 spd_Aligned.sortedByCoord.out.bam \-c chr11:-:62646614-62646678:./Mus_musculus.GRCm39.108.gff3 --l1 Spc_rep --l2 Spd_rep -o $output_dir/Sashimi --color '#808080,#000000'

Thank you

**Comment by EricKutschera** [comment]
From the README description for the `-c` argument: https://github.com/Xinglab/rmats2sashimiplot/tree/v2.0.4#all-arguments
> The format is -c {chromosome}:{strand}:{start}:{end}:{/path/to/gff3}

In the code you posted there is a `-` instead of a `:` between the start and end:
-c chr11:-:62646614-62646678:./Mus_musculus.GRCm39.108.gff3

**Comment by Oliverfeudj** [comment]
Thank you for your answer, I didn't notice that mistake 
Now it says this, although rMATS has detected and reported an event with these coordinates:

WARNING: No entries found for gene chrX:70422620:70422671:+ in GFF /home/output/Sashimi/Sashimi_index/tmp.gff3
Skipping gene chrX:70422620:70422671:+...

Exception: Event chrX:70422620:70422671:+ not found in pickled directory /home/output/Sashimi/Sashimi_index. Are you sure this is the right directory for the event?
mv: cannot stat '/home/olivier/Sashimi/Sashimi_plot/chrX:70422620:70422671:+.pdf': No such file or directory

**Comment by EricKutschera** [comment]
rMATS will add `chr` to chromosome names in its output files. It looks like Mus_musculus.GRCm39.108.gff3 uses `X` instead of `chrX`. Can you try updating the command  to use `-c X:...`?

Also the `not found in pickled directory` error can happen when the same value for the output directory is given with `-o` for different runs of rmats2sashimiplot. Can you try using a new output directory or removing the old output directory?

**Comment by Oliverfeudj** [comment]
Yes I have removed the `chr` now I'm figuring out the `not found directory`
I have another question please, how can I extend the coordinates without getting an error, for example, if I write X:+:70421620:70422770, I get the same error but I put a coordinate that has been identified by rMATS it works but the plot does not look quite nice, I want to visualize other exons too by extending the coordinates.

Thank you for your reply

**Comment by EricKutschera** [comment]
That change in the coordinate range should not give an error if the smaller coordinate range output a plot. The larger range should find additional exons if they are there

Are you using a new output directory each time or else deleting the old output directory? If you use the same output directory and also change the coordinates then I think you will get that `not found in pickled directory` because rmats2sashimiplot sees old files from the previous run and gets confused if the coordinates are different

**Comment by Oliverfeudj** [comment]
Yes you are right thank you very much, I close this issue with another question please, is there a way to used logged RPKM in sashimi plots?

**Comment by EricKutschera** [comment]
Here's the place in the code where the values plotted as RPKM are calculated: https://github.com/Xinglab/rmats2sashimiplot/blob/v2.0.4/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py#L88

You could write those values to a log file if you want to use them for something other than the plot

**Comment by Oliverfeudj** [comment]
Thank you, but I want to output the sashimi plots from rmats2sashimiplot with log2(RPKM) on the y-axis instead of RPKM as it's the case with the current version

**Comment by EricKutschera** [comment]
There isn't a command line option for that, but you can modify a few lines of the code:

There is a setting for plotting log base 10 output that you could set to true: https://github.com/Xinglab/rmats2sashimiplot/blob/v2.0.4/src/rmats2sashimiplot/rmats2sashimiplot.py#L167

If you want log base 2 then you can change `log10` to `log2` here: https://github.com/Xinglab/rmats2sashimiplot/blob/v2.0.4/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py#L100

The axis label is updated here if you want to change that: https://github.com/Xinglab/rmats2sashimiplot/blob/v2.0.4/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py#L459

**Comment by Oliverfeudj** [comment]
Thank you very much
